import Head from 'next/head';
import type { AppProps } from 'next/app';
import styles from 'styles/app.module.scss';
import 'styles/global/globals.scss';

const App = ({ Component, pageProps }: AppProps) => (
  <div className={styles.container}>
    <Head>
      <title>Todo App with NextJS</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <Component {...pageProps} />
    </main>
  </div>
);

export default App;
